DROP TABLE SIMPLE_TRACKER.AVERAGE;

CREATE TABLE SIMPLE_TRACKER.AVERAGE (
  date          DATE          NOT NULL,
  average       DOUBLE(5,2)   NOT NULL
);

ALTER TABLE SIMPLE_TRACKER.AVERAGE ADD PRIMARY KEY (date);